apiVersion: v1
kind: ConfigMap
metadata:
  name: interview-q-a-agent-config
  namespace: {{ .Values.namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  S3_ENDPOINT_URL: {{ .Values.s3EndpointUrl | quote }}
  S3_BUCKET_NAME: {{ .Values.s3BucketName | quote }}
  S3_REGION_NAME: {{ .Values.s3RegionName | quote }}