apiVersion: v1
kind: Secret
metadata:
  name: interview-q-a-agent-secret
  namespace: {{ .Values.namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.openaiApiKey | b64enc | quote }}
  SERPAPI_API_KEY: {{ .Values.serpapiApiKey | b64enc | quote }}
  S3_ACCESS_KEY_ID: {{ .Values.s3AccessKeyId | b64enc | quote }}
  S3_SECRET_ACCESS_KEY: {{ .Values.s3SecretAccessKey | b64enc | quote }}